Repository Nilphym/cryptocurrency-exchange, pull requests merged in 2021-01, with the labels that each got.

#1 Project basic setup
  .gitignore
  .yarn/releases/yarn-berry.cjs
  .yarnrc.yml
  README.md
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
  yarn.lock
Labels: enhancement

#2 Changelog and contribution documentation
  CHANGELOG.md
  CONTRIBUTION.md
Labels: documentation

#6 Feature/sass integration
  CHANGELOG.md
  package.json
  src/App.js
  src/App.scss
  src/App.test.js
  src/index.css
  src/index.js
  src/index.scss
  yarn.lock
Labels: enhancement

#9 Add react router with example
  CHANGELOG.md
  package.json
  src/App.js
  src/components/About.js
  src/components/Home.js
  yarn.lock
Labels: enhancement

#7 superlinter.yml config for github action as CI
  .github/workflows/superlinter.yml
  CHANGELOG.md
  src/App.js
  src/App.test.js
Labels: enhancement

#8 Storybook for developing components
  .storybook/main.js
  .storybook/preview.js
  CHANGELOG.md
  package.json
  src/components/Button/Button.js
  src/components/Button/Button.stories.js
  src/components/Button/button.css
  src/components/Header/Header.js
  src/components/Header/Header.stories.js
  src/components/Header/header.css
  src/components/Page/Page.js
  src/components/Page/Page.stories.js
  src/components/Page/page.css
  yarn.lock
Labels: enhancement

#10 Fix husky config in package.json
  CHANGELOG.md
  package.json
Labels: bug
